import { CpuAddressingMode, CpuCycle, CpuInstructionType, CpuOpcode } from '/@/types'
import { UnknownOpcodeError } from '/@/errors'
import { Instruction } from '/@/models/Cpu/Instruction'

// see: http://obelisk.me.uk/6502/reference.html
// see: https://wiki.nesdev.com/w/index.php/Programming_with_unofficial_opcodes
// see: http://www.oxyron.de/html/opcodes02.html
const instructionArgs: [CpuOpcode, CpuInstructionType, CpuAddressingMode, CpuCycle, number, boolean][] = [
  [0x00, CpuInstructionType.Brk, CpuAddressingMode.Implicit, 7, 1, true],
  [0x01, CpuInstructionType.Ora, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0x02, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x03, CpuInstructionType.Slo, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0x04, CpuInstructionType.Nop, CpuAddressingMode.ZeroPage, 3, 2, false],
  [0x05, CpuInstructionType.Ora, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x06, CpuInstructionType.Asl, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0x07, CpuInstructionType.Slo, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0x08, CpuInstructionType.Php, CpuAddressingMode.Implicit, 3, 1, true],
  [0x09, CpuInstructionType.Ora, CpuAddressingMode.Immediate, 2, 2, true],
  [0x0a, CpuInstructionType.Asl, CpuAddressingMode.Accumulator, 2, 1, true],
  // [0x0b, InstructionType.anc, AddressingMode.immediate, 2, 2, false],
  [0x0c, CpuInstructionType.Nop, CpuAddressingMode.Absolute, 4, 3, false],
  [0x0d, CpuInstructionType.Ora, CpuAddressingMode.Absolute, 4, 3, true],
  [0x0e, CpuInstructionType.Asl, CpuAddressingMode.Absolute, 6, 3, true],
  [0x0f, CpuInstructionType.Slo, CpuAddressingMode.Absolute, 6, 3, false],
  [0x10, CpuInstructionType.Bpl, CpuAddressingMode.Relative, 2, 2, true],
  [0x11, CpuInstructionType.Ora, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0x12, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x13, CpuInstructionType.Slo, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0x14, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0x15, CpuInstructionType.Ora, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x16, CpuInstructionType.Asl, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0x17, CpuInstructionType.Slo, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0x18, CpuInstructionType.Clc, CpuAddressingMode.Implicit, 2, 1, true],
  [0x19, CpuInstructionType.Ora, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0x1a, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0x1b, CpuInstructionType.Slo, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0x1c, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0x1d, CpuInstructionType.Ora, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0x1e, CpuInstructionType.Asl, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0x1f, CpuInstructionType.Slo, CpuAddressingMode.AbsoluteX, 7, 3, false],
  [0x20, CpuInstructionType.Jsr, CpuAddressingMode.Absolute, 6, 3, true],
  [0x21, CpuInstructionType.And, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0x22, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x23, CpuInstructionType.Rla, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0x24, CpuInstructionType.Bit, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x25, CpuInstructionType.And, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x26, CpuInstructionType.Rol, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0x27, CpuInstructionType.Rla, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0x28, CpuInstructionType.Plp, CpuAddressingMode.Implicit, 4, 1, true],
  [0x29, CpuInstructionType.And, CpuAddressingMode.Immediate, 2, 2, true],
  [0x2a, CpuInstructionType.Rol, CpuAddressingMode.Accumulator, 2, 1, true],
  // [0x2b, InstructionType.anc, AddressingMode.immediate, 2, 2, false],
  [0x2c, CpuInstructionType.Bit, CpuAddressingMode.Absolute, 4, 3, true],
  [0x2d, CpuInstructionType.And, CpuAddressingMode.Absolute, 4, 3, true],
  [0x2e, CpuInstructionType.Rol, CpuAddressingMode.Absolute, 6, 3, true],
  [0x2f, CpuInstructionType.Rla, CpuAddressingMode.Absolute, 6, 3, false],
  [0x30, CpuInstructionType.Bmi, CpuAddressingMode.Relative, 2, 2, true],
  [0x31, CpuInstructionType.And, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0x32, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x33, CpuInstructionType.Rla, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0x34, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0x35, CpuInstructionType.And, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x36, CpuInstructionType.Rol, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0x37, CpuInstructionType.Rla, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0x38, CpuInstructionType.Sec, CpuAddressingMode.Implicit, 2, 1, true],
  [0x39, CpuInstructionType.And, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0x3a, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0x3b, CpuInstructionType.Rla, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0x3c, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0x3d, CpuInstructionType.And, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0x3e, CpuInstructionType.Rol, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0x3f, CpuInstructionType.Rla, CpuAddressingMode.AbsoluteX, 7, 3, false],
  [0x40, CpuInstructionType.Rti, CpuAddressingMode.Implicit, 6, 1, true],
  [0x41, CpuInstructionType.Eor, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0x42, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x43, CpuInstructionType.Sre, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0x44, CpuInstructionType.Nop, CpuAddressingMode.ZeroPage, 3, 2, false],
  [0x45, CpuInstructionType.Eor, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x46, CpuInstructionType.Lsr, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0x47, CpuInstructionType.Sre, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0x48, CpuInstructionType.Pha, CpuAddressingMode.Implicit, 3, 1, true],
  [0x49, CpuInstructionType.Eor, CpuAddressingMode.Immediate, 2, 2, true],
  [0x4a, CpuInstructionType.Lsr, CpuAddressingMode.Accumulator, 2, 1, true],
  // [0x4b, InstructionType.alr, AddressingMode.immediate, 2, 2, false],
  [0x4c, CpuInstructionType.Jmp, CpuAddressingMode.Absolute, 3, 3, true],
  [0x4d, CpuInstructionType.Eor, CpuAddressingMode.Absolute, 4, 3, true],
  [0x4e, CpuInstructionType.Lsr, CpuAddressingMode.Absolute, 6, 3, true],
  [0x4f, CpuInstructionType.Sre, CpuAddressingMode.Absolute, 6, 3, false],
  [0x50, CpuInstructionType.Bvc, CpuAddressingMode.Relative, 2, 2, true],
  [0x51, CpuInstructionType.Eor, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0x52, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x53, CpuInstructionType.Sre, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0x54, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0x55, CpuInstructionType.Eor, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x56, CpuInstructionType.Lsr, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0x57, CpuInstructionType.Sre, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0x58, CpuInstructionType.Cli, CpuAddressingMode.Implicit, 2, 1, true],
  [0x59, CpuInstructionType.Eor, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0x5a, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0x5b, CpuInstructionType.Sre, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0x5c, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0x5d, CpuInstructionType.Eor, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0x5e, CpuInstructionType.Lsr, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0x5f, CpuInstructionType.Sre, CpuAddressingMode.AbsoluteX, 7, 3, false],
  [0x60, CpuInstructionType.Rts, CpuAddressingMode.Implicit, 6, 1, true],
  [0x61, CpuInstructionType.Adc, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0x62, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x63, CpuInstructionType.Rra, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0x64, CpuInstructionType.Nop, CpuAddressingMode.ZeroPage, 3, 2, false],
  [0x65, CpuInstructionType.Adc, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x66, CpuInstructionType.Ror, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0x67, CpuInstructionType.Rra, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0x68, CpuInstructionType.Pla, CpuAddressingMode.Implicit, 4, 1, true],
  [0x69, CpuInstructionType.Adc, CpuAddressingMode.Immediate, 2, 2, true],
  [0x6a, CpuInstructionType.Ror, CpuAddressingMode.Accumulator, 2, 1, true],
  // [0x6b, InstructionType.arr, AddressingMode.immediate, 2, 2, false],
  [0x6c, CpuInstructionType.Jmp, CpuAddressingMode.Indirect, 5, 3, true],
  [0x6d, CpuInstructionType.Adc, CpuAddressingMode.Absolute, 4, 3, true],
  [0x6e, CpuInstructionType.Ror, CpuAddressingMode.Absolute, 6, 3, true],
  [0x6f, CpuInstructionType.Rra, CpuAddressingMode.Absolute, 6, 3, false],
  [0x70, CpuInstructionType.Bvs, CpuAddressingMode.Relative, 2, 2, true],
  [0x71, CpuInstructionType.Adc, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0x72, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0x73, CpuInstructionType.Rra, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0x74, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0x75, CpuInstructionType.Adc, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x76, CpuInstructionType.Ror, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0x77, CpuInstructionType.Rra, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0x78, CpuInstructionType.Sei, CpuAddressingMode.Implicit, 2, 1, true],
  [0x79, CpuInstructionType.Adc, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0x7a, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0x7b, CpuInstructionType.Rra, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0x7c, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0x7d, CpuInstructionType.Adc, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0x7e, CpuInstructionType.Ror, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0x7f, CpuInstructionType.Rra, CpuAddressingMode.AbsoluteX, 7, 3, false],
  [0x80, CpuInstructionType.Nop, CpuAddressingMode.Immediate, 2, 2, false],
  [0x81, CpuInstructionType.Sta, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0x82, InstructionType.nop, AddressingMode.immediate, 2, 2, false],
  [0x83, CpuInstructionType.Sax, CpuAddressingMode.IndexedIndirect, 6, 2, false],
  [0x84, CpuInstructionType.Sty, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x85, CpuInstructionType.Sta, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x86, CpuInstructionType.Stx, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0x87, CpuInstructionType.Sax, CpuAddressingMode.ZeroPage, 3, 2, false],
  [0x88, CpuInstructionType.Dey, CpuAddressingMode.Implicit, 2, 1, true],
  // [0x89, InstructionType.nop, AddressingMode.immediate, 2, 2, false],
  [0x8a, CpuInstructionType.Txa, CpuAddressingMode.Implicit, 2, 1, true],
  // [0x8b, InstructionType.xaa, AddressingMode.immediate, 2, 2, false],
  [0x8c, CpuInstructionType.Sty, CpuAddressingMode.Absolute, 4, 3, true],
  [0x8d, CpuInstructionType.Sta, CpuAddressingMode.Absolute, 4, 3, true],
  [0x8e, CpuInstructionType.Stx, CpuAddressingMode.Absolute, 4, 3, true],
  [0x8f, CpuInstructionType.Sax, CpuAddressingMode.Absolute, 4, 3, false],
  [0x90, CpuInstructionType.Bcc, CpuAddressingMode.Relative, 2, 2, true],
  [0x91, CpuInstructionType.Sta, CpuAddressingMode.IndirectIndexed, 6, 2, true],
  // [0x92, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  // [0x93, InstructionType.ahx, AddressingMode.indirectIndexed, 6, 2, false],
  [0x94, CpuInstructionType.Sty, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x95, CpuInstructionType.Sta, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0x96, CpuInstructionType.Stx, CpuAddressingMode.ZeroPageY, 4, 2, true],
  [0x97, CpuInstructionType.Sax, CpuAddressingMode.ZeroPageY, 4, 2, false],
  [0x98, CpuInstructionType.Tya, CpuAddressingMode.Implicit, 2, 1, true],
  [0x99, CpuInstructionType.Sta, CpuAddressingMode.AbsoluteY, 5, 3, true],
  [0x9a, CpuInstructionType.Txs, CpuAddressingMode.Implicit, 2, 1, true],
  // [0x9b, InstructionType.tas, AddressingMode.absoluteY, 5, 3, false],
  // [0x9c, InstructionType.shy, AddressingMode.absoluteX, 5, 3, false],
  [0x9d, CpuInstructionType.Sta, CpuAddressingMode.AbsoluteX, 5, 3, true],
  // [0x9e, InstructionType.shx, AddressingMode.absoluteY, 5, 3, false],
  // [0x9f, InstructionType.ahx, AddressingMode.absoluteY, 5, 3, false],
  [0xa0, CpuInstructionType.Ldy, CpuAddressingMode.Immediate, 2, 2, true],
  [0xa1, CpuInstructionType.Lda, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  [0xa2, CpuInstructionType.Ldx, CpuAddressingMode.Immediate, 2, 2, true],
  [0xa3, CpuInstructionType.Lax, CpuAddressingMode.IndexedIndirect, 6, 2, false],
  [0xa4, CpuInstructionType.Ldy, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xa5, CpuInstructionType.Lda, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xa6, CpuInstructionType.Ldx, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xa7, CpuInstructionType.Lax, CpuAddressingMode.ZeroPage, 3, 2, false],
  [0xa8, CpuInstructionType.Tay, CpuAddressingMode.Implicit, 2, 1, true],
  [0xa9, CpuInstructionType.Lda, CpuAddressingMode.Immediate, 2, 2, true],
  [0xaa, CpuInstructionType.Tax, CpuAddressingMode.Implicit, 2, 1, true],
  // [0xab, InstructionType.lax, AddressingMode.immediate, 2, 2, false],
  [0xac, CpuInstructionType.Ldy, CpuAddressingMode.Absolute, 4, 3, true],
  [0xad, CpuInstructionType.Lda, CpuAddressingMode.Absolute, 4, 3, true],
  [0xae, CpuInstructionType.Ldx, CpuAddressingMode.Absolute, 4, 3, true],
  [0xaf, CpuInstructionType.Lax, CpuAddressingMode.Absolute, 4, 3, false],
  [0xb0, CpuInstructionType.Bcs, CpuAddressingMode.Relative, 2, 2, true],
  [0xb1, CpuInstructionType.Lda, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0xb2, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0xb3, CpuInstructionType.Lax, CpuAddressingMode.IndirectIndexed, 5, 2, false],
  [0xb4, CpuInstructionType.Ldy, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0xb5, CpuInstructionType.Lda, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0xb6, CpuInstructionType.Ldx, CpuAddressingMode.ZeroPageY, 4, 2, true],
  [0xb7, CpuInstructionType.Lax, CpuAddressingMode.ZeroPageY, 4, 2, false],
  [0xb8, CpuInstructionType.Clv, CpuAddressingMode.Implicit, 2, 1, true],
  [0xb9, CpuInstructionType.Lda, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0xba, CpuInstructionType.Tsx, CpuAddressingMode.Implicit, 2, 1, true],
  // [0xbb, InstructionType.las, AddressingMode.absoluteY, 4, 3, false],
  [0xbc, CpuInstructionType.Ldy, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0xbd, CpuInstructionType.Lda, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0xbe, CpuInstructionType.Ldx, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0xbf, CpuInstructionType.Lax, CpuAddressingMode.AbsoluteY, 4, 3, false],
  [0xc0, CpuInstructionType.Cpy, CpuAddressingMode.Immediate, 2, 2, true],
  [0xc1, CpuInstructionType.Cmp, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0xc2, InstructionType.nop, AddressingMode.immediate, 2, 2, false],
  [0xc3, CpuInstructionType.Dcp, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0xc4, CpuInstructionType.Cpy, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xc5, CpuInstructionType.Cmp, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xc6, CpuInstructionType.Dec, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0xc7, CpuInstructionType.Dcp, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0xc8, CpuInstructionType.Iny, CpuAddressingMode.Implicit, 2, 1, true],
  [0xc9, CpuInstructionType.Cmp, CpuAddressingMode.Immediate, 2, 2, true],
  [0xca, CpuInstructionType.Dex, CpuAddressingMode.Implicit, 2, 1, true],
  // [0xcb, InstructionType.axs, AddressingMode.immediate, 2, 2, false],
  [0xcc, CpuInstructionType.Cpy, CpuAddressingMode.Absolute, 4, 3, true],
  [0xcd, CpuInstructionType.Cmp, CpuAddressingMode.Absolute, 4, 3, true],
  [0xce, CpuInstructionType.Dec, CpuAddressingMode.Absolute, 6, 3, true],
  [0xcf, CpuInstructionType.Dcp, CpuAddressingMode.Absolute, 6, 3, false],
  [0xd0, CpuInstructionType.Bne, CpuAddressingMode.Relative, 2, 2, true],
  [0xd1, CpuInstructionType.Cmp, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0xd2, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0xd3, CpuInstructionType.Dcp, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0xd4, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0xd5, CpuInstructionType.Cmp, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0xd6, CpuInstructionType.Dec, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0xd7, CpuInstructionType.Dcp, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0xd8, CpuInstructionType.Cld, CpuAddressingMode.Implicit, 2, 1, true],
  [0xd9, CpuInstructionType.Cmp, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0xda, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0xdb, CpuInstructionType.Dcp, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0xdc, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0xdd, CpuInstructionType.Cmp, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0xde, CpuInstructionType.Dec, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0xdf, CpuInstructionType.Dcp, CpuAddressingMode.AbsoluteX, 7, 3, false],
  [0xe0, CpuInstructionType.Cpx, CpuAddressingMode.Immediate, 2, 2, true],
  [0xe1, CpuInstructionType.Sbc, CpuAddressingMode.IndexedIndirect, 6, 2, true],
  // [0xe2, InstructionType.nop, AddressingMode.immediate, 2, 2, false],
  [0xe3, CpuInstructionType.Isb, CpuAddressingMode.IndexedIndirect, 8, 2, false],
  [0xe4, CpuInstructionType.Cpx, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xe5, CpuInstructionType.Sbc, CpuAddressingMode.ZeroPage, 3, 2, true],
  [0xe6, CpuInstructionType.Inc, CpuAddressingMode.ZeroPage, 5, 2, true],
  [0xe7, CpuInstructionType.Isb, CpuAddressingMode.ZeroPage, 5, 2, false],
  [0xe8, CpuInstructionType.Inx, CpuAddressingMode.Implicit, 2, 1, true],
  [0xe9, CpuInstructionType.Sbc, CpuAddressingMode.Immediate, 2, 2, true],
  [0xea, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, true],
  [0xeb, CpuInstructionType.Sbc, CpuAddressingMode.Immediate, 2, 2, false],
  [0xec, CpuInstructionType.Cpx, CpuAddressingMode.Absolute, 4, 3, true],
  [0xed, CpuInstructionType.Sbc, CpuAddressingMode.Absolute, 4, 3, true],
  [0xee, CpuInstructionType.Inc, CpuAddressingMode.Absolute, 6, 3, true],
  [0xef, CpuInstructionType.Isb, CpuAddressingMode.Absolute, 6, 3, false],
  [0xf0, CpuInstructionType.Beq, CpuAddressingMode.Relative, 2, 2, true],
  [0xf1, CpuInstructionType.Sbc, CpuAddressingMode.IndirectIndexed, 5, 2, true],
  // [0xf2, InstructionType.kil, AddressingMode.implicit, 0, 1, false],
  [0xf3, CpuInstructionType.Isb, CpuAddressingMode.IndirectIndexed, 8, 2, false],
  [0xf4, CpuInstructionType.Nop, CpuAddressingMode.ZeroPageX, 4, 2, false],
  [0xf5, CpuInstructionType.Sbc, CpuAddressingMode.ZeroPageX, 4, 2, true],
  [0xf6, CpuInstructionType.Inc, CpuAddressingMode.ZeroPageX, 6, 2, true],
  [0xf7, CpuInstructionType.Isb, CpuAddressingMode.ZeroPageX, 6, 2, false],
  [0xf8, CpuInstructionType.Sed, CpuAddressingMode.Implicit, 2, 1, true],
  [0xf9, CpuInstructionType.Sbc, CpuAddressingMode.AbsoluteY, 4, 3, true],
  [0xfa, CpuInstructionType.Nop, CpuAddressingMode.Implicit, 2, 1, false],
  [0xfb, CpuInstructionType.Isb, CpuAddressingMode.AbsoluteY, 7, 3, false],
  [0xfc, CpuInstructionType.Nop, CpuAddressingMode.AbsoluteX, 4, 3, false],
  [0xfd, CpuInstructionType.Sbc, CpuAddressingMode.AbsoluteX, 4, 3, true],
  [0xfe, CpuInstructionType.Inc, CpuAddressingMode.AbsoluteX, 7, 3, true],
  [0xff, CpuInstructionType.Isb, CpuAddressingMode.AbsoluteX, 7, 3, false],
]

class InstructionSet {
  private instructions = instructionArgs.map((args) => new Instruction(...args))

  findByOpcode(opcode: Uint8): Instruction {
    const instruction = this.instructions.find((instruction) => instruction.opcode === opcode)

    if (!instruction) throw new UnknownOpcodeError(opcode)

    return instruction
  }
}

const instructionSet = new InstructionSet()

export { instructionSet as InstructionSet }
