import { AddressingMode, Cycle, InstructionType, Opcode } from '/@/types'
import { UnknownOpcodeError } from '/@/errors'
import Instruction from '/@/models/Instruction'

// see: http://obelisk.me.uk/6502/reference.html
const instructionArgs: [Opcode, InstructionType, AddressingMode, Cycle, boolean][] = [
  [0x00, InstructionType.brk, AddressingMode.implicit, 7, false],
  [0x01, InstructionType.ora, AddressingMode.indexedIndirect, 6, false],
  // [0x02, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x04, InstructionType.slo, AddressingMode.indexedIndirect, 8, false],
  [0x04, InstructionType.nop, AddressingMode.zeroPage, 3, false],
  [0x05, InstructionType.ora, AddressingMode.zeroPage, 3, false],
  [0x06, InstructionType.asl, AddressingMode.zeroPage, 5, false],
  // [0x07, InstructionType.slo, AddressingMode.zeroPage, 5, false],
  [0x08, InstructionType.php, AddressingMode.implicit, 3, false],
  [0x09, InstructionType.ora, AddressingMode.immediate, 2, false],
  [0x0a, InstructionType.asl, AddressingMode.accumulator, 2, false],
  // [0x0b, InstructionType.anc, AddressingMode.immediate, 2, false],
  [0x0c, InstructionType.nop, AddressingMode.absolute, 4, false],
  [0x0d, InstructionType.ora, AddressingMode.absolute, 4, false],
  [0x0e, InstructionType.asl, AddressingMode.absolute, 6, false],
  // [0x0f, InstructionType.slo, AddressingMode.absolute, 6, false],
  [0x10, InstructionType.bpl, AddressingMode.relative, 2, true],
  [0x11, InstructionType.ora, AddressingMode.indirectIndexed, 5, true],
  // [0x12, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x13, InstructionType.slo, AddressingMode.indirectIndexed, 8, false],
  [0x14, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0x15, InstructionType.ora, AddressingMode.zeroPageX, 4, false],
  [0x16, InstructionType.asl, AddressingMode.zeroPageX, 6, false],
  // [0x17, InstructionType.slo, AddressingMode.zeroPageX, 6, false],
  [0x18, InstructionType.clc, AddressingMode.implicit, 2, false],
  [0x19, InstructionType.ora, AddressingMode.absoluteY, 4, true],
  [0x1a, InstructionType.nop, AddressingMode.implicit, 2, false],
  // [0x1b, InstructionType.slo, AddressingMode.absoluteY, 7, false],
  [0x1c, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0x1d, InstructionType.ora, AddressingMode.absoluteX, 4, true],
  [0x1e, InstructionType.asl, AddressingMode.absoluteX, 7, false],
  // [0x1f, InstructionType.slo, AddressingMode.absoluteX, 7, false],
  [0x21, InstructionType.jsr, AddressingMode.absolute, 6, false],
  [0x21, InstructionType.and, AddressingMode.indexedIndirect, 6, false],
  // [0x22, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x23, InstructionType.rla, AddressingMode.indexedIndirect, 8, false],
  [0x24, InstructionType.bit, AddressingMode.zeroPage, 3, false],
  [0x25, InstructionType.and, AddressingMode.zeroPage, 3, false],
  [0x26, InstructionType.rol, AddressingMode.zeroPage, 5, false],
  // [0x27, InstructionType.rla, AddressingMode.zeroPage, 5, false],
  [0x28, InstructionType.plp, AddressingMode.implicit, 4, false],
  [0x29, InstructionType.and, AddressingMode.immediate, 2, false],
  [0x2a, InstructionType.rol, AddressingMode.accumulator, 2, false],
  // [0x2b, InstructionType.anc, AddressingMode.immediate, 2, false],
  [0x2c, InstructionType.bit, AddressingMode.absolute, 4, false],
  [0x2d, InstructionType.and, AddressingMode.absolute, 4, false],
  [0x2e, InstructionType.rol, AddressingMode.absolute, 6, false],
  // [0x2f, InstructionType.rla, AddressingMode.absolute, 6, false],
  [0x30, InstructionType.bmi, AddressingMode.relative, 2, true],
  [0x31, InstructionType.and, AddressingMode.indirectIndexed, 5, true],
  // [0x32, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x33, InstructionType.rla, AddressingMode.indirectIndexed, 8, false],
  [0x34, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0x35, InstructionType.and, AddressingMode.zeroPageX, 4, false],
  [0x36, InstructionType.rol, AddressingMode.zeroPageX, 6, false],
  // [0x37, InstructionType.rla, AddressingMode.zeroPageX, 6, false],
  [0x38, InstructionType.sec, AddressingMode.implicit, 2, false],
  [0x39, InstructionType.and, AddressingMode.absoluteY, 4, true],
  [0x3a, InstructionType.nop, AddressingMode.implicit, 2, false],
  // [0x3b, InstructionType.rla, AddressingMode.absoluteY, 7, false],
  [0x3c, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0x3d, InstructionType.and, AddressingMode.absoluteX, 4, true],
  [0x3e, InstructionType.rol, AddressingMode.absoluteX, 7, false],
  // [0x3f, InstructionType.rla, AddressingMode.absoluteX, 7, false],
  [0x40, InstructionType.rti, AddressingMode.implicit, 6, false],
  [0x41, InstructionType.eor, AddressingMode.indexedIndirect, 6, false],
  // [0x42, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x43, InstructionType.sre, AddressingMode.indexedIndirect, 8, false],
  [0x44, InstructionType.nop, AddressingMode.zeroPage, 3, false],
  [0x45, InstructionType.eor, AddressingMode.zeroPage, 3, false],
  [0x46, InstructionType.lsr, AddressingMode.zeroPage, 5, false],
  // [0x47, InstructionType.sre, AddressingMode.zeroPage, 5, false],
  [0x48, InstructionType.pha, AddressingMode.implicit, 3, false],
  [0x49, InstructionType.eor, AddressingMode.immediate, 2, false],
  [0x4a, InstructionType.lsr, AddressingMode.accumulator, 2, false],
  // [0x4b, InstructionType.alr, AddressingMode.immediate, 2, false],
  [0x4c, InstructionType.jmp, AddressingMode.absolute, 3, false],
  [0x4d, InstructionType.eor, AddressingMode.absolute, 4, false],
  [0x4e, InstructionType.lsr, AddressingMode.absolute, 6, false],
  // [0x4f, InstructionType.sre, AddressingMode.absolute, 6, false],
  [0x50, InstructionType.bvc, AddressingMode.relative, 2, true],
  [0x51, InstructionType.eor, AddressingMode.indirectIndexed, 5, true],
  // [0x52, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x53, InstructionType.sre, AddressingMode.indirectIndexed, 8, false],
  [0x54, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0x55, InstructionType.eor, AddressingMode.zeroPageX, 4, false],
  [0x56, InstructionType.lsr, AddressingMode.zeroPageX, 6, false],
  // [0x57, InstructionType.sre, AddressingMode.zeroPageX, 6, false],
  [0x58, InstructionType.cli, AddressingMode.implicit, 2, false],
  [0x59, InstructionType.eor, AddressingMode.absoluteY, 4, true],
  [0x5a, InstructionType.nop, AddressingMode.implicit, 2, false],
  // [0x5b, InstructionType.sre, AddressingMode.absoluteY, 7, false],
  [0x5c, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0x5d, InstructionType.eor, AddressingMode.absoluteX, 4, true],
  [0x5e, InstructionType.lsr, AddressingMode.absoluteX, 7, false],
  // [0x5f, InstructionType.sre, AddressingMode.absoluteX, 7, false],
  [0x60, InstructionType.rts, AddressingMode.implicit, 6, false],
  [0x61, InstructionType.adc, AddressingMode.indexedIndirect, 6, false],
  // [0x62, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x63, InstructionType.rra, AddressingMode.indexedIndirect, 8, false],
  [0x64, InstructionType.nop, AddressingMode.zeroPage, 3, false],
  [0x65, InstructionType.adc, AddressingMode.zeroPage, 3, false],
  [0x66, InstructionType.ror, AddressingMode.zeroPage, 5, false],
  // [0x67, InstructionType.rra, AddressingMode.zeroPage, 5, false],
  [0x68, InstructionType.pla, AddressingMode.implicit, 4, false],
  [0x69, InstructionType.adc, AddressingMode.immediate, 2, false],
  [0x6a, InstructionType.ror, AddressingMode.accumulator, 2, false],
  // [0x6b, InstructionType.arr, AddressingMode.immediate, 2, false],
  [0x6c, InstructionType.jmp, AddressingMode.indirect, 5, false],
  [0x6d, InstructionType.adc, AddressingMode.absolute, 4, false],
  [0x6e, InstructionType.ror, AddressingMode.absolute, 6, false],
  // [0x6f, InstructionType.rra, AddressingMode.absolute, 6, false],
  [0x70, InstructionType.bvs, AddressingMode.relative, 2, true],
  [0x71, InstructionType.adc, AddressingMode.indirectIndexed, 5, true],
  // [0x72, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x73, InstructionType.rra, AddressingMode.indirectIndexed, 8, false],
  [0x74, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0x75, InstructionType.adc, AddressingMode.zeroPageX, 4, false],
  [0x76, InstructionType.ror, AddressingMode.zeroPageX, 6, false],
  // [0x77, InstructionType.rra, AddressingMode.zeroPageX, 6, false],
  [0x78, InstructionType.sei, AddressingMode.implicit, 2, false],
  [0x79, InstructionType.adc, AddressingMode.absoluteY, 4, true],
  [0x7a, InstructionType.nop, AddressingMode.implicit, 2, false],
  // [0x7b, InstructionType.rra, AddressingMode.absoluteY, 7, false],
  [0x7c, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0x7d, InstructionType.adc, AddressingMode.absoluteX, 4, true],
  [0x7e, InstructionType.ror, AddressingMode.absoluteX, 7, false],
  // [0x7f, InstructionType.rra, AddressingMode.absoluteX, 7, false],
  [0x80, InstructionType.nop, AddressingMode.immediate, 2, false],
  [0x81, InstructionType.sta, AddressingMode.indexedIndirect, 6, false],
  [0x82, InstructionType.nop, AddressingMode.immediate, 2, false],
  // [0x83, InstructionType.sax, AddressingMode.indexedIndirect, 6, false],
  [0x84, InstructionType.sty, AddressingMode.zeroPage, 3, false],
  [0x85, InstructionType.sta, AddressingMode.zeroPage, 3, false],
  [0x86, InstructionType.stx, AddressingMode.zeroPage, 3, false],
  // [0x87, InstructionType.sax, AddressingMode.zeroPage, 3, false],
  [0x88, InstructionType.dey, AddressingMode.implicit, 2, false],
  [0x89, InstructionType.nop, AddressingMode.immediate, 2, false],
  [0x8a, InstructionType.txa, AddressingMode.implicit, 2, false],
  // [0x8b, InstructionType.xaa, AddressingMode.immediate, 2, false],
  [0x8c, InstructionType.sty, AddressingMode.absolute, 4, false],
  [0x8d, InstructionType.sta, AddressingMode.absolute, 4, false],
  [0x8e, InstructionType.stx, AddressingMode.absolute, 4, false],
  // [0x8f, InstructionType.sax, AddressingMode.absolute, 4, false],
  [0x90, InstructionType.bcc, AddressingMode.relative, 2, true],
  [0x91, InstructionType.sta, AddressingMode.indirectIndexed, 6, false],
  // [0x92, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0x93, InstructionType.ahx, AddressingMode.indirectIndexed, 6, false],
  [0x94, InstructionType.sty, AddressingMode.zeroPageX, 4, false],
  [0x95, InstructionType.sta, AddressingMode.zeroPageX, 4, false],
  [0x96, InstructionType.stx, AddressingMode.zeroPageY, 4, false],
  // [0x97, InstructionType.sax, AddressingMode.zeroPageY, 4, false],
  [0x98, InstructionType.tya, AddressingMode.implicit, 2, false],
  [0x99, InstructionType.sta, AddressingMode.absoluteY, 5, false],
  [0x9a, InstructionType.txs, AddressingMode.implicit, 2, false],
  // [0x9b, InstructionType.tas, AddressingMode.absoluteY, 5, false],
  // [0x9c, InstructionType.shy, AddressingMode.absoluteX, 5, false],
  [0x9d, InstructionType.sta, AddressingMode.absoluteX, 5, false],
  // [0x9e, InstructionType.shx, AddressingMode.absoluteY, 5, false],
  // [0x9f, InstructionType.ahx, AddressingMode.absoluteY, 5, false],
  [0xa0, InstructionType.ldy, AddressingMode.immediate, 2, false],
  [0xa1, InstructionType.lda, AddressingMode.indexedIndirect, 6, false],
  [0xa2, InstructionType.ldx, AddressingMode.immediate, 2, false],
  // [0xa3, InstructionType.lax, AddressingMode.indexedIndirect, 6, false],
  [0xa4, InstructionType.ldy, AddressingMode.zeroPage, 3, false],
  [0xa5, InstructionType.lda, AddressingMode.zeroPage, 3, false],
  [0xa6, InstructionType.ldx, AddressingMode.zeroPage, 3, false],
  // [0xa7, InstructionType.lax, AddressingMode.zeroPage, 3, false],
  [0xa8, InstructionType.tay, AddressingMode.implicit, 2, false],
  [0xa9, InstructionType.lda, AddressingMode.immediate, 2, false],
  [0xaa, InstructionType.tax, AddressingMode.implicit, 2, false],
  // [0xab, InstructionType.lax, AddressingMode.immediate, 2, false],
  [0xac, InstructionType.ldy, AddressingMode.absolute, 4, false],
  [0xad, InstructionType.lda, AddressingMode.absolute, 4, false],
  [0xae, InstructionType.ldx, AddressingMode.absolute, 4, false],
  // [0xaf, InstructionType.lax, AddressingMode.absolute, 4, false],
  [0xb0, InstructionType.bcs, AddressingMode.relative, 2, true],
  [0xb1, InstructionType.lda, AddressingMode.indirectIndexed, 5, true],
  // [0xb2, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0xb3, InstructionType.lax, AddressingMode.indirectIndexed, 5, true],
  [0xb4, InstructionType.ldy, AddressingMode.zeroPageX, 4, false],
  [0xb5, InstructionType.lda, AddressingMode.zeroPageX, 4, false],
  [0xb6, InstructionType.ldx, AddressingMode.zeroPageY, 4, false],
  // [0xb7, InstructionType.lax, AddressingMode.zeroPageY, 4, false],
  [0xb8, InstructionType.clv, AddressingMode.implicit, 2, false],
  [0xb9, InstructionType.lda, AddressingMode.absoluteY, 4, true],
  [0xba, InstructionType.tsx, AddressingMode.implicit, 2, false],
  // [0xbb, InstructionType.las, AddressingMode.absoluteY, 4, true],
  [0xbc, InstructionType.ldy, AddressingMode.absoluteX, 4, true],
  [0xbd, InstructionType.lda, AddressingMode.absoluteX, 4, true],
  [0xbe, InstructionType.ldx, AddressingMode.absoluteY, 4, true],
  // [0xbf, InstructionType.lax, AddressingMode.absoluteY, 4, true],
  [0xc0, InstructionType.cpy, AddressingMode.immediate, 2, false],
  [0xc1, InstructionType.cmp, AddressingMode.indexedIndirect, 6, false],
  [0xc2, InstructionType.nop, AddressingMode.immediate, 2, false],
  // [0xc3, InstructionType.dcp, AddressingMode.indexedIndirect, 8, false],
  [0xc4, InstructionType.cpy, AddressingMode.zeroPage, 3, false],
  [0xc5, InstructionType.cmp, AddressingMode.zeroPage, 3, false],
  [0xc6, InstructionType.dec, AddressingMode.zeroPage, 5, false],
  // [0xc7, InstructionType.dcp, AddressingMode.zeroPage, 5, false],
  [0xc8, InstructionType.iny, AddressingMode.implicit, 2, false],
  [0xc9, InstructionType.cmp, AddressingMode.immediate, 2, false],
  [0xca, InstructionType.dex, AddressingMode.implicit, 2, false],
  // [0xcb, InstructionType.axs, AddressingMode.immediate, 2, false],
  [0xcc, InstructionType.cpy, AddressingMode.absolute, 4, false],
  [0xcd, InstructionType.cmp, AddressingMode.absolute, 4, false],
  [0xce, InstructionType.dec, AddressingMode.absolute, 6, false],
  // [0xcf, InstructionType.dcp, AddressingMode.absolute, 6, false],
  [0xd0, InstructionType.bne, AddressingMode.relative, 2, true],
  [0xd1, InstructionType.cmp, AddressingMode.indirectIndexed, 5, true],
  // [0xd2, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0xd3, InstructionType.dcp, AddressingMode.indirectIndexed, 8, false],
  [0xd4, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0xd5, InstructionType.cmp, AddressingMode.zeroPageX, 4, false],
  [0xd6, InstructionType.dec, AddressingMode.zeroPageX, 6, false],
  // [0xd7, InstructionType.dcp, AddressingMode.zeroPageX, 6, false],
  [0xd8, InstructionType.cld, AddressingMode.implicit, 2, false],
  [0xd9, InstructionType.cmp, AddressingMode.absoluteY, 4, true],
  [0xda, InstructionType.nop, AddressingMode.implicit, 2, false],
  // [0xdb, InstructionType.dcp, AddressingMode.absoluteY, 7, false],
  [0xdc, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0xdd, InstructionType.cmp, AddressingMode.absoluteX, 4, true],
  [0xde, InstructionType.dec, AddressingMode.absoluteX, 7, false],
  // [0xdf, InstructionType.dcp, AddressingMode.absoluteX, 7, false],
  [0xe0, InstructionType.cpx, AddressingMode.immediate, 2, false],
  [0xe1, InstructionType.sbc, AddressingMode.indexedIndirect, 6, false],
  [0xe2, InstructionType.nop, AddressingMode.immediate, 2, false],
  // [0xe3, InstructionType.isc, AddressingMode.indexedIndirect, 8, false],
  [0xe4, InstructionType.cpx, AddressingMode.zeroPage, 3, false],
  [0xe5, InstructionType.sbc, AddressingMode.zeroPage, 3, false],
  [0xe6, InstructionType.inc, AddressingMode.zeroPage, 5, false],
  // [0xe7, InstructionType.isc, AddressingMode.zeroPage, 5, false],
  [0xe8, InstructionType.inx, AddressingMode.implicit, 2, false],
  [0xe9, InstructionType.sbc, AddressingMode.immediate, 2, false],
  [0xea, InstructionType.nop, AddressingMode.implicit, 2, false],
  [0xeb, InstructionType.sbc, AddressingMode.immediate, 2, false],
  [0xec, InstructionType.cpx, AddressingMode.absolute, 4, false],
  [0xed, InstructionType.sbc, AddressingMode.absolute, 4, false],
  [0xee, InstructionType.inc, AddressingMode.absolute, 6, false],
  // [0xef, InstructionType.isc, AddressingMode.absolute, 6, false],
  [0xf0, InstructionType.beq, AddressingMode.relative, 2, true],
  [0xf1, InstructionType.sbc, AddressingMode.indirectIndexed, 5, true],
  // [0xf2, InstructionType.kil, AddressingMode.implicit, 0, false],
  // [0xf3, InstructionType.isc, AddressingMode.indirectIndexed, 8, false],
  [0xf4, InstructionType.nop, AddressingMode.zeroPageX, 4, false],
  [0xf5, InstructionType.sbc, AddressingMode.zeroPageX, 4, false],
  [0xf6, InstructionType.inc, AddressingMode.zeroPageX, 6, false],
  //s [0xf7, InstructionType.isc, AddressingMode.zeroPageX, 6, false],
  [0xf8, InstructionType.sed, AddressingMode.implicit, 2, false],
  [0xf9, InstructionType.sbc, AddressingMode.absoluteY, 4, true],
  [0xfa, InstructionType.nop, AddressingMode.implicit, 2, false],
  //s [0xfb, InstructionType.isc, AddressingMode.absoluteY, 7, false],
  [0xfc, InstructionType.nop, AddressingMode.absoluteX, 4, true],
  [0xfd, InstructionType.sbc, AddressingMode.absoluteX, 4, true],
  [0xfe, InstructionType.inc, AddressingMode.absoluteX, 7, false],
  // [0xff, InstructionType.isc, AddressingMode.absoluteX, 7, false],
]

class InstructionSet {
  private instructions = instructionArgs.map((args) => new Instruction(...args))

  findByOpcode(opcode: Uint8): Instruction {
    const instruction = this.instructions.find((instruction) => instruction.opcode === opcode)

    if (!instruction) throw new UnknownOpcodeError(opcode)

    return instruction
  }
}

export default new InstructionSet()
